version: '3.9'

services:
  auth:
    container_name: auth
    build: ./auth
    env_file:
      - ./env/auth/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:14-alpine
    volumes:
      - /data:/var/lib/postgresql/data
    env_file:
      - ./env/pg/.env
  redis:
    container_name: redis
    image: redis:7.0-alpine
    restart: always
    volumes:
      - redis_data:/data
  nginx:
    container_name: nginx
    image: nginx:1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - auth
volumes:
  postgres_data:
  redis_data:
