Endpoint to delete role
---
tags:
- DELETE_ROLE
description: delete role
parameters:
- name: role_id
  in: path
  required: true
  description: Role uuid
  schema:
    type: string
  example:
    role_id: a9c6e8da-f2bf-458a-978b-d2f50a031451
responses:
  204:
    description: role was deleted successfully
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Response'
        example:
          status: success
          message: role was deleted successfully
  401:
    $ref: '#/components/responses/Unauthorized'
  403:
    $ref: '#/components/responses/Forbidden'
  404:
    $ref: '#/components/responses/NotFound'
security:
  - jwt_auth:
    - write:admin
    - read:admin