Endpoint to get all roles
---
tags:
  - ROLE_LIST
description: List of all available roles
responses:
  200:
    description: List of roles is available
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/Role'
          example:
            - id: a9c6e8da-f2bf-458a-978b-d2f50a031451
              code: admin
              description: unlimited access to all actions
            - id: 7cf56926-054c-4522-ac6f-d9f5d0e9d18e
              code: subscriber
              description: account without paying for registered users
            - id: 7166fd5f-a4e4-45f0-952c-78d0297c7b03
              code: member
              description: account with payment options
  401:
    $ref: '#/components/responses/Unauthorized'
  403:
    $ref: '#/components/responses/Forbidden'
  404:
    $ref: '#/components/responses/NotFound'